spring:
  datasource:
    # O Drive com.mysql.jdbc.Driver foi depreciado
    #driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vendas?useTimezone=true&serverTimezone=UTC
    username: aula
    password: aula
  jpa:
    databasePlatform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        showSql: true
        formatSql: true

server:
  port: 8080
  servlet:
    context-path: /vendas

