CREATE DATABASE IF NOT EXISTS VENDAS;

USE VENDAS;

DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS ITENS_PEDIDOS;
DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS PRODUTOS;
DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES (
    CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRIMARY KEY (CLIENTE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUTOS (
    PRODUTO INT NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO_UNITARIO DECIMAL(19,2),
    PRIMARY KEY (PRODUTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PEDIDOS (
    PEDIDO INT NOT NULL AUTO_INCREMENT,
    CLIENTE INT NOT NULL,
    DATA_PEDIDO DATETIME NOT NULL,
    TOTAL DECIMAL(19,2),
    PRIMARY KEY (PEDIDO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CLIENTE);

CREATE TABLE ITENS_PEDIDOS (
    ITEM_PEDIDO INT NOT NULL AUTO_INCREMENT,
    PEDIDO INT NOT NULL,
    PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ITEM_PEDIDO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ITENS_PEDIDOS ADD CONSTRAINT FK_ITENS_PEDIDOS_PEDIDO FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS (PEDIDO);
ALTER TABLE ITENS_PEDIDOS ADD CONSTRAINT FK_ITENS_PEDIDOS_PRODUTO FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS (PRODUTO);

CREATE TABLE USUARIOS (
    USUARIO INT NOT NULL AUTO_INCREMENT,
    LOGIN VARCHAR(100) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN TINYINT DEFAULT 0,
    PRIMARY KEY (USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;